// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NOT_FOUND - -1]
	_ = x[ILLEGAL-0]
	_ = x[WHITESPACE-1]
	_ = x[COMMENT-2]
	_ = x[EOF-3]
	_ = x[literals_begin-4]
	_ = x[IDENT-5]
	_ = x[INT-6]
	_ = x[FLOAT-7]
	_ = x[BOOL_TRUE-8]
	_ = x[BOOL_FALSE-9]
	_ = x[STRING-10]
	_ = x[literals_end-11]
	_ = x[keywords_begin-12]
	_ = x[STRUCT-13]
	_ = x[TYPE-14]
	_ = x[LET-15]
	_ = x[SET-16]
	_ = x[TRUE-17]
	_ = x[FALSE-18]
	_ = x[NIL-19]
	_ = x[keywords_end-20]
	_ = x[symbols_begin-21]
	_ = x[LBRACKET-22]
	_ = x[RBRACKET-23]
	_ = x[LBRACE-24]
	_ = x[RBRACE-25]
	_ = x[LPAREN-26]
	_ = x[RPAREN-27]
	_ = x[PERIOD-28]
	_ = x[COMMA-29]
	_ = x[SEMICOLON-30]
	_ = x[COLON-31]
	_ = x[EQ-32]
	_ = x[ARROW-33]
	_ = x[symbols_end-34]
}

const _TokenType_name = "NOT_FOUNDILLEGALWHITESPACECOMMENTEOFliterals_beginIDENTINTFLOATBOOL_TRUEBOOL_FALSESTRINGliterals_endkeywords_beginSTRUCTTYPELETSETTRUEFALSENILkeywords_endsymbols_beginLBRACKETRBRACKETLBRACERBRACELPARENRPARENPERIODCOMMASEMICOLONCOLONEQARROWsymbols_end"

var _TokenType_index = [...]uint8{0, 9, 16, 26, 33, 36, 50, 55, 58, 63, 72, 82, 88, 100, 114, 120, 124, 127, 130, 134, 139, 142, 154, 167, 175, 183, 189, 195, 201, 207, 213, 218, 227, 232, 234, 239, 250}

func (i TokenType) String() string {
	i -= -1
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
