// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NOT_FOUND - -1]
	_ = x[ILLEGAL-0]
	_ = x[WHITESPACE-1]
	_ = x[COMMENT-2]
	_ = x[EOF-3]
	_ = x[IDENT-4]
	_ = x[literals_begin-5]
	_ = x[INT-6]
	_ = x[FLOAT-7]
	_ = x[STRING-8]
	_ = x[literals_end-9]
	_ = x[keywords_begin-10]
	_ = x[STRUCT-11]
	_ = x[TYPE-12]
	_ = x[LET-13]
	_ = x[SET-14]
	_ = x[TRUE-15]
	_ = x[FALSE-16]
	_ = x[NIL-17]
	_ = x[AND-18]
	_ = x[OR-19]
	_ = x[NOT-20]
	_ = x[FUNC-21]
	_ = x[keywords_end-22]
	_ = x[symbols_begin-23]
	_ = x[LBRACKET-24]
	_ = x[RBRACKET-25]
	_ = x[LBRACE-26]
	_ = x[RBRACE-27]
	_ = x[LPAREN-28]
	_ = x[RPAREN-29]
	_ = x[PERIOD-30]
	_ = x[COMMA-31]
	_ = x[SEMICOLON-32]
	_ = x[COLON-33]
	_ = x[EQ-34]
	_ = x[ARROW-35]
	_ = x[PLUS-36]
	_ = x[MINUS-37]
	_ = x[STAR-38]
	_ = x[SLASH-39]
	_ = x[GT-40]
	_ = x[LT-41]
	_ = x[GTEQ-42]
	_ = x[LTEQ-43]
	_ = x[symbols_end-44]
}

const _TokenType_name = "NOT_FOUNDILLEGALWHITESPACECOMMENTEOFIDENTliterals_beginINTFLOATSTRINGliterals_endkeywords_beginSTRUCTTYPELETSETTRUEFALSENILANDORNOTFUNCkeywords_endsymbols_beginLBRACKETRBRACKETLBRACERBRACELPARENRPARENPERIODCOMMASEMICOLONCOLONEQARROWPLUSMINUSSTARSLASHGTLTGTEQLTEQsymbols_end"

var _TokenType_index = [...]uint16{0, 9, 16, 26, 33, 36, 41, 55, 58, 63, 69, 81, 95, 101, 105, 108, 111, 115, 120, 123, 126, 128, 131, 135, 147, 160, 168, 176, 182, 188, 194, 200, 206, 211, 220, 225, 227, 232, 236, 241, 245, 250, 252, 254, 258, 262, 273}

func (i TokenType) String() string {
	i -= -1
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
