// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NOT_FOUND - -1]
	_ = x[ILLEGAL-0]
	_ = x[WHITESPACE-1]
	_ = x[COMMENT-2]
	_ = x[EOF-3]
	_ = x[IDENT-4]
	_ = x[literals_begin-5]
	_ = x[INT-6]
	_ = x[FLOAT-7]
	_ = x[STRING-8]
	_ = x[literals_end-9]
	_ = x[keywords_begin-10]
	_ = x[STRUCT-11]
	_ = x[TYPE-12]
	_ = x[LET-13]
	_ = x[SET-14]
	_ = x[TRUE-15]
	_ = x[FALSE-16]
	_ = x[NIL-17]
	_ = x[keywords_end-18]
	_ = x[symbols_begin-19]
	_ = x[LBRACKET-20]
	_ = x[RBRACKET-21]
	_ = x[LBRACE-22]
	_ = x[RBRACE-23]
	_ = x[LPAREN-24]
	_ = x[RPAREN-25]
	_ = x[PERIOD-26]
	_ = x[COMMA-27]
	_ = x[SEMICOLON-28]
	_ = x[COLON-29]
	_ = x[EQ-30]
	_ = x[ARROW-31]
	_ = x[PLUS-32]
	_ = x[MINUS-33]
	_ = x[STAR-34]
	_ = x[SLASH-35]
	_ = x[symbols_end-36]
}

const _TokenType_name = "NOT_FOUNDILLEGALWHITESPACECOMMENTEOFIDENTliterals_beginINTFLOATSTRINGliterals_endkeywords_beginSTRUCTTYPELETSETTRUEFALSENILkeywords_endsymbols_beginLBRACKETRBRACKETLBRACERBRACELPARENRPARENPERIODCOMMASEMICOLONCOLONEQARROWPLUSMINUSSTARSLASHsymbols_end"

var _TokenType_index = [...]uint8{0, 9, 16, 26, 33, 36, 41, 55, 58, 63, 69, 81, 95, 101, 105, 108, 111, 115, 120, 123, 135, 148, 156, 164, 170, 176, 182, 188, 194, 199, 208, 213, 215, 220, 224, 229, 233, 238, 249}

func (i TokenType) String() string {
	i -= -1
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
